site_name: Rick's Work Notes
# nav:
#   - 'Storage'
theme: 
  name: material
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.sticky
    # - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - header.autohide
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: blue grey
      accent: grey 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: white
      accent: black
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rickkoe
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rickkoetter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rickkoetter/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/rickkoe"  target="_blank" rel="noopener">Rick Koetter</a>
